=== mcroissant/sila_base/schema/FeatureDefinition.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" 
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:tns="http://www.sila-standard.org"
    xmlns:dta="http://www.sila-standard.org/Data"
    targetNamespace="http://www.sila-standard.org">
  <xs:import namespace="http://www.sila-standard.org/Data" schemaLocation="DataTypeType.xsd"/>
  <xs:element name="Feature">
    <xs:complexType>
      <!-- Feature Content -->
      <xs:sequence>
        <xs:element type="tns:IdentifierType" name="Identifier" />
        <xs:element type="tns:DisplayNameType" name="DisplayName" />
        <xs:element type="xs:string" name="Description" />
        <!-- @Note: xs:all can not be used here, as it doesn't allow unbounded occurences -->
        <xs:choice maxOccurs="unbounded">
          <xs:element name="Command" maxOccurs="unbounded" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element type="tns:IdentifierType" name="Identifier" />
                <xs:element type="tns:DisplayNameType" name="DisplayName" />
                <xs:element type="xs:string" name="Description" />
                <xs:element name="Observable">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:enumeration value="Yes" />
                      <xs:enumeration value="No" />
                    </xs:restriction>
                  </xs:simpleType>
                </xs:element>
                <xs:element type="tns:SiLAElement" name="Parameter" maxOccurs="unbounded" minOccurs="0" />
                <xs:element type="tns:SiLAElement" name="Response" maxOccurs="unbounded" minOccurs="0" />
                <xs:element type="tns:SiLAElement" name="IntermediateResponse" maxOccurs="unbounded" minOccurs="0" />
                <xs:element name="StandardExecutionErrors" maxOccurs="1" minOccurs="0">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element type="tns:IdentifierType" name="StandardExecutionErrorIdentifier" maxOccurs="unbounded" minOccurs="1" />
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="StandardExecutionError" maxOccurs="unbounded" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element type="tns:IdentifierType" name="Identifier" />
                <xs:element type="tns:DisplayNameType" name="DisplayName" />
                <xs:element type="xs:string" name="Description" />
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="Property" maxOccurs="unbounded" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element type="tns:IdentifierType" name="Identifier" />
                <xs:element type="tns:DisplayNameType" name="DisplayName" />
                <xs:element type="xs:string" name="Description" />
                <xs:element type="dta:DataTypeType" name="DataType" />
                <xs:element name="Observable">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:enumeration value="Yes" />
                      <xs:enumeration value="No" />
                    </xs:restriction>
                  </xs:simpleType>
                </xs:element>
                <xs:element name="StandardReadErrors" maxOccurs="1" minOccurs="0">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element type="tns:IdentifierType" name="StandardReadErrorIdentifier" maxOccurs="unbounded" minOccurs="1" />
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="StandardReadError" maxOccurs="unbounded" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element type="tns:IdentifierType" name="Identifier" />
                <xs:element type="tns:DisplayNameType" name="DisplayName" />
                <xs:element type="xs:string" name="Description" />
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element type="tns:SiLAElement" name="DataTypeDefinition" maxOccurs="unbounded" minOccurs="0" />
        </xs:choice>
      </xs:sequence>

      <!-- Attributes -->
      <xs:attribute type="xs:string" name="Locale" use="optional" default="en-us" />
      <xs:attribute name="SiLA2Version" use="required">
        <xs:simpleType>
          <xs:restriction base ="xs:string">
            <xs:pattern value="\d+\.\d+" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="FeatureVersion" use="required">
        <xs:simpleType>
          <xs:restriction base ="xs:string">
            <xs:pattern value="\d+\.\d+" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="MaturityLevel" use="optional" default="Draft">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Draft" />
            <xs:enumeration value="Verified" />
            <xs:enumeration value="Normative" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="Originator" use="required">
        <xs:simpleType>
          <xs:restriction base ="xs:string">
            <xs:pattern value="[a-z][a-z\.]*" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="Category" use="optional">
        <xs:simpleType>
          <xs:restriction base ="xs:string">
            <xs:pattern value="[a-z][a-z\.]*" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <!-- XSD Internal Types -->
  <xs:simpleType name="IdentifierType">
    <xs:restriction base ="xs:string">
      <xs:pattern value="[A-Z][a-zA-Z0-9]*" />
      <xs:maxLength value="255" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="DisplayNameType">
    <xs:restriction base ="xs:string">
      <xs:maxLength value="255" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="SiLAElement">
    <xs:sequence>
      <xs:element type="tns:IdentifierType" name="Identifier" />
      <xs:element type="tns:DisplayNameType" name="DisplayName" />
      <xs:element type="xs:string" name="Description" />
      <xs:element type="dta:DataTypeType" name="DataType" />
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="BasicType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="String"/>
      <xs:enumeration value="Integer"/>
      <xs:enumeration value="Real"/>
      <xs:enumeration value="Boolean"/>
      <xs:enumeration value="SmallBinary"/>
      <xs:enumeration value="Date"/>
      <xs:enumeration value="Time"/>
      <xs:enumeration value="Timestamp"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="ListType">
    <xs:sequence>
      <xs:element type="dta:DataTypeType" name="DataType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="StructureType">
    <xs:sequence>
      <xs:element type="tns:SiLAElement" name = "Element" maxOccurs="unbounded" minOccurs="1" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== mcroissant/sila_base/feature_definitions/ch/unitelabs/ProgramController.sila.xml
<?xml version="1.0" encoding="utf-8" ?>
<Feature SiLA2Version="0.1" FeatureVersion="1.0" Originator="ch.unitelabs"
         xmlns="http://www.sila-standard.org"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.sila-standard.org https://gitlab.com/SiLA2/sila_features/raw/master/schema/FeatureDefinition.xsd">
    <Identifier>ProgramController</Identifier>
    <DisplayName>Program  Controller</DisplayName>
    <Description>
        Exposes the ability to start, stop and pause pre-defined programs saved in the
        instrument. For example: a liquid handling machine, microscope, plate reader.
    </Description>
    <!-- Commands -->
    <Command>
        <Identifier>Run</Identifier>
        <DisplayName>Run</DisplayName>
        <Description>
            Starts a program with a known name and provides an optional stream for progress updates. There shall be no response. See List Programs command to get the list of existing programs.
        </Description>
        <Observable>Yes</Observable>
        <Parameter>
            <Identifier>ProgramName</Identifier>
            <DisplayName>ProgramName</DisplayName>
            <Description>The name of the program to start.</Description>
            <DataType>
                <Basic>String</Basic>
            </DataType>
        </Parameter>
        <StandardExecutionErrors>
            <StandardExecutionErrorIdentifier>InvalidState</StandardExecutionErrorIdentifier>
        </StandardExecutionErrors>
    </Command>
    <Command>
        <Identifier>Stop</Identifier>
        <DisplayName>Stop</DisplayName>
        <Description>Stops a currently running program, without a possibility to resume.</Description>
        <Observable>No</Observable>
        <StandardExecutionErrors>
            <StandardExecutionErrorIdentifier>InvalidState</StandardExecutionErrorIdentifier>
        </StandardExecutionErrors>
    </Command>
    <Command>
        <Identifier>ListPrograms</Identifier>
        <DisplayName>List Programs</DisplayName>
        <Description>Returns the list of currently available programs saved in the device.</Description>
        <Observable>No</Observable>
        <Response>
            <Identifier>ProgramList</Identifier>
            <DisplayName>Program list</DisplayName>
            <Description>List of the saved programs available to run on the device.</Description>
            <DataType>
                <List>
                    <DataType>
                        <Basic>String</Basic>
                    </DataType>
                </List>
            </DataType>
        </Response>
    </Command>
    <!-- Command Execution Errors -->
    <StandardExecutionError>
        <Identifier>InvalidState</Identifier>
        <DisplayName>Invalid State</DisplayName>
        <Description>
            The command cannot be issued as the server is not in the correct
            state.
        </Description>
    </StandardExecutionError>
</Feature>

=== mcroissant/sila_base/feature_definitions/de/tuberlin/bioprocess/StorageService.xml
<?xml version="1.0" encoding="utf-8" ?>
<Feature SiLAVersion="2" MajorVersion="1" MinorVersion="0" MaturityLevel="Draft" Originator="de.tuberlin.bioprocess" UseCase="storing"
        xmlns="http://www.sila-standard.org" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.sila-standard.org https://gitlab.com/SiLA2/sila_features/raw/master/schema/FeatureDefinition.xsd">
    <Identifier>StorageService</Identifier>
    <DisplayName>Storage Service</DisplayName>
    <Description>This Service provides commands and informations neede to control a storage device</Description>
    <Command>
        <Identifier>GetLabwareInformation</Identifier>
        <DisplayName>Get Labware Information</DisplayName>
        <Description>Which labware is mounted in the differnt tower of the device</Description>
        <Observable>No</Observable>
        <Parameter>
            <Identifier>AttainablePosition</Identifier>
            <DisplayName>Attainable Position</DisplayName>
            <Description>Retuns the information of the labware at the requested position as Labware Type according to the SiLA Labware Specification Standard (Version 1.0)</Description>
            <DataType>
                 <Basic>Integer</Basic>
            </DataType>
        </Parameter>
        <Response>
            <Identifier>LabwareType</Identifier>
            <DisplayName>Labware Type</DisplayName>
            <Description>Labware Type according to the SiLA Labware Specification Standard (Version 1.0)</Description>
            <DataType>
                <Basic>Integer</Basic>
            </DataType>
        </Response>
        <StandardExecutionErrors>
            <StandardExecutionErrorIdentifier>InvalidPosition</StandardExecutionErrorIdentifier>
        </StandardExecutionErrors>
    </Command>
    <Command>
        <Identifier>SetLabwareInformation</Identifier>
        <DisplayName>Set Labware Information</DisplayName>
        <Description>Which labware is mounted in the different tower of the device</Description>
        <Observable>No</Observable>
        <Parameter>
            <Identifier>AttainablePosition</Identifier>
            <DisplayName>Attainable Position</DisplayName>
            <Description>Sets the information of the labware of the at the addressed position as Labware Type according to the SiLA Labware Specification Standard (Version 1.0)</Description>
            <DataType>
                 <Basic>Integer</Basic>
            </DataType>
        </Parameter>
        <Response>
            <Identifier>LabwareType</Identifier>
            <DisplayName>Labware Type</DisplayName>
            <Description>Labware Type according to the SiLA Labware Specification Standard (Version 1.0)</Description>
            <DataType>
                <Basic>Integer</Basic>
            </DataType>
        </Response>
        <StandardExecutionErrors>
          <StandardExecutionErrorIdentifier>InvalidPosition</StandardExecutionErrorIdentifier>
        </StandardExecutionErrors>
    </Command>
    <Command>
     <Identifier>GetFromPosition</Identifier>
     <DisplayName>Get From Position</DisplayName>
     <Description>Get a Labware from the specified position and presents it to the addressed handover position</Description>
     <Observable>No</Observable>
     <Parameter>
       <Identifier>AttainablePosition</Identifier>
       <DisplayName>Attainable Position</DisplayName>
       <Description>Postion of the labware in the storage device</Description>
       <DataType>
         <Basic>Integer</Basic>
       </DataType>
     </Parameter>
     <Response>
       <Identifier>HandoverPosition</Identifier>
       <DisplayName>Handover Postion</DisplayName>
       <Description>Postion of the labware handover</Description>
       <DataType>
         <Basic>Integer</Basic>
       </DataType>
     </Response>
     <StandardExecutionErrors>
       <StandardExecutionErrorIdentifier>InvalidPosition</StandardExecutionErrorIdentifier>
     </StandardExecutionErrors>
   </Command>
    <Command>
     <Identifier>PutToPosition</Identifier>
     <DisplayName>PutToPosition</DisplayName>
     <Description>Take a labware from the addressed handover position an stores it at the specified position</Description>
     <Observable>No</Observable>
     <Parameter>
       <Identifier>AttainablePosition</Identifier>
       <DisplayName>Attainable Position</DisplayName>
       <Description>Postion in the storage device where the labware will be stored</Description>
       <DataType>
         <Basic>Integer</Basic>
       </DataType>
     </Parameter>
     <Response>
       <Identifier>HandoverPosition</Identifier>
       <DisplayName>Handover Postion</DisplayName>
       <Description>Postion of the labware handover</Description>
       <DataType>
         <Basic>Integer</Basic>
       </DataType>
     </Response>
     <StandardExecutionErrors>
       <StandardExecutionErrorIdentifier>InvalidPosition</StandardExecutionErrorIdentifier>
     </StandardExecutionErrors>
    </Command>
    <StandardExecutionError>
        <Identifier>InvalidPosition</Identifier>
        <DisplayName>Invalid Position</DisplayName>
        <Description>Somethings happens what better should not happend</Description>
    </StandardExecutionError>
    <Property>
        <Identifier>TowerNumber</Identifier>
        <DisplayName>Tower Number</DisplayName>
        <Description>The addressed Position is not attainable or unknown at this device</Description>
        <DataType>
            <Basic>Integer</Basic>
        </DataType>
        <PropertyType>Static</PropertyType>
    </Property>
    <Property>
        <Identifier>HandoverNumber</Identifier>
        <DisplayName>Handover Number</DisplayName>
        <Description>The number of positions where a labware could be committed</Description>
        <DataType>
            <Basic>Integer</Basic>
        </DataType>
        <PropertyType>Static</PropertyType>
    </Property>
    <Property>
        <Identifier>AttainablePositions</Identifier>
        <DisplayName>Attainable Positions</DisplayName>
        <Description>The number of positions which could be attained directly by the device</Description>
        <DataType>
            <Basic>Integer</Basic>
        </DataType>
        <PropertyType>Static</PropertyType>
    </Property>
</Feature>

=== mcroissant/sila_base/feature_definitions/de/tuberlin/bioprocess/Storage/StorageProvider.xml
<?xml version="1.0" encoding="utf-8" ?>
<Feature SiLAVersion="2" MajorVersion="1" MinorVersion="0" MaturityLevel="Draft" Originator="de.tuberlin.bioprocess" UseCase="storing"
        xmlns="http://www.sila-standard.org" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.sila-standard.org https://gitlab.com/SiLA2/sila_features/raw/master/schema/FeatureDefinition.xsd">
    <Identifier>StorageProvider</Identifier>
    <DisplayName>Storage Provider</DisplayName>
    <Description>Provides all information of a storage devices</Description>
    <Command>
        <Identifier>GetLabwareInformation</Identifier>
        <DisplayName>Get Labware Information</DisplayName>
        <Description>Which labware is mounted in the differnt tower of the device</Description>
        <Observable>No</Observable>
        <Parameter>
            <Identifier>AttainablePosition</Identifier>
            <DisplayName>Attainable Position</DisplayName>
            <Description>Retuns the information of the labware at the requested position as Labware Type according to the SiLA Labware Specification Standard (Version 1.0)</Description>
            <DataType>
                 <Basic>Integer</Basic>
            </DataType>
        </Parameter>
        <Response>
            <Identifier>LabwareType</Identifier>
            <DisplayName>Labware Type</DisplayName>
            <Description>Labware Type according to the SiLA Labware Specification Standard (Version 1.0)</Description>
            <DataType>
                <Basic>Integer</Basic>
            </DataType>
        </Response>
        <StandardExecutionErrors>
            <StandardExecutionErrorIdentifier>InvalidPosition</StandardExecutionErrorIdentifier>
        </StandardExecutionErrors>
    </Command>
    <Command>
        <Identifier>SetLabwareInformation</Identifier>
        <DisplayName>Set Labware Information</DisplayName>
        <Description>Which labware is mounted in the different tower of the device</Description>
        <Observable>No</Observable>
        <Parameter>
            <Identifier>AttainablePosition</Identifier>
            <DisplayName>Attainable Position</DisplayName>
            <Description>Sets the information of the labware of the at the addressed position as Labware Type according to the SiLA Labware Specification Standard (Version 1.0)</Description>
            <DataType>
                 <Basic>Integer</Basic>
            </DataType>
        </Parameter>
        <Response>
            <Identifier>LabwareType</Identifier>
            <DisplayName>Labware Type</DisplayName>
            <Description>Labware Type according to the SiLA Labware Specification Standard (Version 1.0)</Description>
            <DataType>
                <Basic>Integer</Basic>
            </DataType>
        </Response>
        <StandardExecutionErrors>
          <StandardExecutionErrorIdentifier>InvalidPosition</StandardExecutionErrorIdentifier>
        </StandardExecutionErrors>
    </Command>
    <StandardExecutionError>
        <Identifier>InvalidPosition</Identifier>
        <DisplayName>Invalid Position</DisplayName>
        <Description>Somethings happens what better should not happend</Description>
    </StandardExecutionError>
    <Property>
        <Identifier>TowerNumber</Identifier>
        <DisplayName>Tower Number</DisplayName>
        <Description>The addressed Position is not attainable or unknown at this device</Description>
        <DataType>
            <Basic>Integer</Basic>
        </DataType>
        <PropertyType>Static</PropertyType>
    </Property>
    <Property>
        <Identifier>HandoverNumber</Identifier>
        <DisplayName>Handover Number</DisplayName>
        <Description>The number of positions where a labware could be committed</Description>
        <DataType>
            <Basic>Integer</Basic>
        </DataType>
        <PropertyType>Static</PropertyType>
    </Property>
    <Property>
        <Identifier>AttainablePositions</Identifier>
        <DisplayName>Attainable Positions</DisplayName>
        <Description>The number of positions which could be attained directly by the device</Description>
        <DataType>
            <Basic>Integer</Basic>
        </DataType>
        <PropertyType>Static</PropertyType>
    </Property>
</Feature>

=== mcroissant/sila_base/feature_definitions/com/madisoft/reader/LuminescenceReaderService.xml
<?xml version="1.0" encoding="utf-8" ?>
<Feature SiLA2Version="0.1" FeatureVersion="1.0" Originator="com.madisoft" Category="reader"
        xmlns="http://www.sila-standard.org"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.sila-standard.org https://gitlab.com/SiLA2/sila_features/raw/master/schema/FeatureDefinition.xsd">
    <Identifier>LuminescenceReaderService</Identifier>
    <DisplayName>Luminescence Reader Service</DisplayName>
    <Description>SiLA 2 Device Luminescence Reader feature - Show basic operations for a device luminescence reader: reading from
        selected well of a plate and reading all wells in a plate. Luminescence reading has an integration property from 0.1 to 10 seconds.
    </Description>
    <!-- Commands -->
    <Command>
        <Identifier>LuminescenceReadWell</Identifier>
        <DisplayName>Luminescence Read Well</DisplayName>
        <Description>Read and present data from one target well</Description>
        <Observable>No</Observable>
        <Parameter>
            <Identifier>TargetWell</Identifier>
            <DisplayName>Target Well</DisplayName>
            <Description>Address of the target well on the plate which the reader will try to find, reach
                and will try to read the well data.
            </Description>
            <DataType>
                <DataTypeIdentifier>WellAddress</DataTypeIdentifier>
            </DataType>
        </Parameter>
        <Response>
            <Identifier>Value</Identifier>
            <DisplayName>Value</DisplayName>
            <Description>Result value of the well</Description>
            <DataType>
                <Basic>Integer</Basic>
            </DataType>
        </Response>
        <StandardExecutionErrors>
            <StandardExecutionErrorIdentifier>WellNotFound</StandardExecutionErrorIdentifier>
            <StandardExecutionErrorIdentifier>ReadInterrupted</StandardExecutionErrorIdentifier>
        </StandardExecutionErrors>
    </Command>
    <Command>
        <Identifier>LuminescenceReadPlate</Identifier>
        <DisplayName>Luminescence Read Plate</DisplayName>
        <Description>Go through every plate well and read its result</Description>
        <Observable>Yes</Observable>
            <Response>
            <Identifier>ResultList</Identifier>
            <DisplayName>Result List Values</DisplayName>
            <Description>Result list of values of every well</Description>
            <DataType>
                <List>
                    <DataType>
                        <Structure>
                            <Element>
                                <Identifier>WellAddress</Identifier>
                                <DisplayName>WellAddress</DisplayName>
                                <Description />
                                <DataType>
                                    <DataTypeIdentifier>WellAddress</DataTypeIdentifier>
                                </DataType>
                            </Element>
                            <Element>
                                <Identifier>Value</Identifier>
                                <DisplayName>Value</DisplayName>
                                <Description>The read luminescence value in this well</Description>
                                <DataType>
                                    <Basic>Integer</Basic>
                                </DataType>
                            </Element>
                        </Structure>
                    </DataType>
                </List>
            </DataType>
        </Response>
        <StandardExecutionErrors>
            <StandardExecutionErrorIdentifier>ReadInterrupted</StandardExecutionErrorIdentifier>
        </StandardExecutionErrors>
    </Command>
    <!-- Properties -->
    <Property>
        <Identifier>Integration</Identifier>
        <DisplayName>Integration</DisplayName>
        <Description>Integration time filter for Luminescence read. It accepts values from 0.1 to 10 seconds.</Description>
        <DataType>
            <Constrained>
                <DataType>
                    <Basic>Real</Basic>
                </DataType>
                <Constraints>
                    <MinimalInclusive>0.1</MinimalInclusive>
                    <MaximalInclusive>10.0</MaximalInclusive>
                </Constraints>
            </Constrained>
        </DataType>
        <Observable>No</Observable>
    </Property>
</Feature>

=== mcroissant/sila_base/feature_definitions/ch/unitelabs/SingleConnectionController.xml
<?xml version="1.0" encoding="utf-8" ?>
<Feature SiLAVersion="2" MajorVersion="1" MinorVersion="0" Originator="ch.unitelabs"
         xmlns="http://www.sila-standard.org"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.sila-standard.org https://gitlab.com/SiLA2/sila_features/raw/master/schema/FeatureDefinition.xsd">
    <Identifier>SingleConnectionController</Identifier>
    <DisplayName>Single Connection Controller</DisplayName>
    <Description>
        Controls and exposes a single connection of the SiLA Server to another component (e.g. an Instrument).
        Note that if this Feature is exposed, it is assumed that the Server doesn't offer the ability
        to control any other connection with this Feature.
    </Description>
    <!-- Commands -->
    <Command>
        <Identifier>Connect</Identifier>
        <DisplayName>Connect</DisplayName>
        <Description>Establish the connection to the component.</Description>
        <Observable>Yes</Observable>
        <StandardExecutionErrors>
            <StandardExecutionErrorIdentifier>ConnectionFailure</StandardExecutionErrorIdentifier>
        </StandardExecutionErrors>
    </Command>
    <Command>
        <Identifier>Disconnect</Identifier>
        <DisplayName>Disconnect</DisplayName>
        <Description>Disconnect from the component.</Description>
        <Observable>Yes</Observable>
        <StandardExecutionErrors>
            <StandardExecutionErrorIdentifier>ConnectionFailure</StandardExecutionErrorIdentifier>
        </StandardExecutionErrors>
    </Command>
    <Property>
        <Identifier>Connected</Identifier>
        <DisplayName>Connected</DisplayName>
        <Description>Represents the connection state, either connected or not.</Description>
        <DataType>
            <Basic>Boolean</Basic>
        </DataType>
        <Observable>Yes</Observable>
    </Property>
    <!-- Command Execution Errors -->
    <StandardExecutionError>
        <Identifier>ConnectionFailure</Identifier>
        <DisplayName>Connection Failure</DisplayName>
        <Description>
            Unable to perform the required connection Command.
        </Description>
    </StandardExecutionError>
</Feature>
