=== mcroissant/sila_base/schema/FeatureDefinition.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" 
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:tns="http://www.sila-standard.org"
    xmlns:dta="http://www.sila-standard.org/Data"
    targetNamespace="http://www.sila-standard.org">
  <xs:import namespace="http://www.sila-standard.org/Data" schemaLocation="DataTypeType.xsd"/>
  <xs:element name="Feature">
    <xs:complexType>
      <!-- Feature Content -->
      <xs:sequence>
        <xs:element type="tns:IdentifierType" name="Identifier" />
        <xs:element type="tns:DisplayNameType" name="DisplayName" />
        <xs:element type="xs:string" name="Description" />
        <!-- @Note: xs:all can not be used here, as it doesn't allow unbounded occurences -->
        <xs:choice maxOccurs="unbounded">
          <xs:element name="Command" maxOccurs="unbounded" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element type="tns:IdentifierType" name="Identifier" />
                <xs:element type="tns:DisplayNameType" name="DisplayName" />
                <xs:element type="xs:string" name="Description" />
                <xs:element name="Observable">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:enumeration value="Yes" />
                      <xs:enumeration value="No" />
                    </xs:restriction>
                  </xs:simpleType>
                </xs:element>
                <xs:element type="tns:SiLAElement" name="Parameter" maxOccurs="unbounded" minOccurs="0" />
                <xs:element type="tns:SiLAElement" name="Response" maxOccurs="unbounded" minOccurs="0" />
                <xs:element type="tns:SiLAElement" name="IntermediateResponse" maxOccurs="unbounded" minOccurs="0" />
                <xs:element name="StandardExecutionErrors" maxOccurs="1" minOccurs="0">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element type="tns:IdentifierType" name="StandardExecutionErrorIdentifier" maxOccurs="unbounded" minOccurs="1" />
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="StandardExecutionError" maxOccurs="unbounded" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element type="tns:IdentifierType" name="Identifier" />
                <xs:element type="tns:DisplayNameType" name="DisplayName" />
                <xs:element type="xs:string" name="Description" />
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="Property" maxOccurs="unbounded" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element type="tns:IdentifierType" name="Identifier" />
                <xs:element type="tns:DisplayNameType" name="DisplayName" />
                <xs:element type="xs:string" name="Description" />
                <xs:element type="dta:DataTypeType" name="DataType" />
                <xs:element name="Observable">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:enumeration value="Yes" />
                      <xs:enumeration value="No" />
                    </xs:restriction>
                  </xs:simpleType>
                </xs:element>
                <xs:element name="StandardReadErrors" maxOccurs="1" minOccurs="0">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element type="tns:IdentifierType" name="StandardReadErrorIdentifier" maxOccurs="unbounded" minOccurs="1" />
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="StandardReadError" maxOccurs="unbounded" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element type="tns:IdentifierType" name="Identifier" />
                <xs:element type="tns:DisplayNameType" name="DisplayName" />
                <xs:element type="xs:string" name="Description" />
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element type="tns:SiLAElement" name="DataTypeDefinition" maxOccurs="unbounded" minOccurs="0" />
        </xs:choice>
      </xs:sequence>

      <!-- Attributes -->
      <xs:attribute type="xs:string" name="Locale" use="optional" default="en-us" />
      <xs:attribute name="SiLA2Version" use="required">
        <xs:simpleType>
          <xs:restriction base ="xs:string">
            <xs:pattern value="\d+\.\d+" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="FeatureVersion" use="required">
        <xs:simpleType>
          <xs:restriction base ="xs:string">
            <xs:pattern value="\d+\.\d+" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="MaturityLevel" use="optional" default="Draft">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Draft" />
            <xs:enumeration value="Verified" />
            <xs:enumeration value="Normative" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="Originator" use="required">
        <xs:simpleType>
          <xs:restriction base ="xs:string">
            <xs:pattern value="[a-z][a-z\.]*" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="Category" use="optional">
        <xs:simpleType>
          <xs:restriction base ="xs:string">
            <xs:pattern value="[a-z][a-z\.]*" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <!-- XSD Internal Types -->
  <xs:simpleType name="IdentifierType">
    <xs:restriction base ="xs:string">
      <xs:pattern value="[A-Z][a-zA-Z0-9]*" />
      <xs:maxLength value="255" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="DisplayNameType">
    <xs:restriction base ="xs:string">
      <xs:maxLength value="255" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="SiLAElement">
    <xs:sequence>
      <xs:element type="tns:IdentifierType" name="Identifier" />
      <xs:element type="tns:DisplayNameType" name="DisplayName" />
      <xs:element type="xs:string" name="Description" />
      <xs:element type="dta:DataTypeType" name="DataType" />
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="BasicType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="String"/>
      <xs:enumeration value="Integer"/>
      <xs:enumeration value="Real"/>
      <xs:enumeration value="Boolean"/>
      <xs:enumeration value="SmallBinary"/>
      <xs:enumeration value="Date"/>
      <xs:enumeration value="Time"/>
      <xs:enumeration value="Timestamp"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="ListType">
    <xs:sequence>
      <xs:element type="dta:DataTypeType" name="DataType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="StructureType">
    <xs:sequence>
      <xs:element type="tns:SiLAElement" name = "Element" maxOccurs="unbounded" minOccurs="1" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== mcroissant/sila_base/feature_definitions/org/silastandard/core/SimulationController.sila.xml
<?xml version="1.0" encoding="utf-8" ?>
<Feature SiLA2Version="1.0" FeatureVersion="1.0" MaturityLevel="Verified" Originator="org.silastandard" Category="core"
         xmlns="http://www.sila-standard.org"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.sila-standard.org https://gitlab.com/SiLA2/sila_base/raw/master/schema/FeatureDefinition.xsd">
    <Identifier>SimulationController</Identifier>
    <DisplayName>Simulation Controller</DisplayName>
    <Description>
        This Feature provides control over the simulation behaviour of a SiLA Server.

        A SiLA Server can run in two modes:
        (a) a real mode - with real activities, e.g. addressing or controlling real hardware,
        writing to real databases, moving real plates etc.
        (b) a simulation mode - where every command is only simulated and responses are just example returns.

        Note that certain commands and properties might not be affected by this feature if they
        do not interact with the real world.
    </Description>
    <Command>
        <Identifier>StartSimulationMode</Identifier>
        <DisplayName>Start Simulation Mode </DisplayName>
        <Description>
			Sets the SiLA Server to run in simulation mode, i.e. all following commands are executed in simulation mode.
			The simulation mode can be stopped by issuing the 'Start Real Mode' command.
		</Description>
        <Observable>No</Observable>
    </Command>
    <Command>
        <Identifier>StartRealMode</Identifier>
        <DisplayName>Start Real Mode</DisplayName>
        <Description>
			Sets the SiLA Server to run in real mode, i.e. all following commands are executed in real mode.
			The real mode can be stopped by issuing the 'Start Simulation Mode' command.
		</Description>
        <Observable>No</Observable>
    </Command>
    <Property>
        <Identifier>SimulationMode</Identifier>
        <DisplayName>SimulationMode</DisplayName>
        <Description>Indication whether SiLA Server is in Simulation Mode or not.</Description>
        <Observable>No</Observable>
        <DataType>
            <Basic>Boolean</Basic>
        </DataType>
    </Property>
</Feature>

=== mcroissant/sila_base/feature_definitions/com/madisoft/reader/CoverController.sila.xml
<?xml version="1.0" encoding="utf-8" ?>
<Feature SiLA2Version="0.1" FeatureVersion="1.0" Originator="com.madisoft" Category="instrument"
         xmlns="http://www.sila-standard.org"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.sila-standard.org https://gitlab.com/SiLA2/sila_features/raw/master/schema/FeatureDefinition.xsd">
    <Identifier>CoverController</Identifier>
    <DisplayName>Cover Controller</DisplayName>
    <Description>General controller to open/close anything that covers the access to an instrument</Description>

    <Command>
        <Identifier>OpenCover</Identifier>
        <DisplayName>Open Cover</DisplayName>
        <Description>Open the device cover</Description>
        <Observable>No</Observable>
    </Command>
    <Command>
        <Identifier>CloseCover</Identifier>
        <DisplayName>Close Cover</DisplayName>
        <Description>Close the device cover</Description>
        <Observable>No</Observable>
    </Command>
</Feature>

=== mcroissant/sila_base/feature_definitions/bg/madisoft/ReaderService.xml
<?xml version="1.0" encoding="utf-8" ?>
<Feature SiLAVersion="2" MajorVersion="1" MinorVersion="0" Originator="org.silastandard" Category="examples"
         xmlns="http://www.sila-standard.org"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.sila-standard.org https://gitlab.com/SiLA2/sila_base/raw/master/schema/FeatureDefinition.xsd">
    <Identifier>ReaderService</Identifier>
    <DisplayName>Reader Service</DisplayName>
    <Description>
        SiLA 2 Reader example
    </Description>
    <Command>
        <Identifier>ReadCell</Identifier>
        <DisplayName>Read Cell</DisplayName>
        <Description>Read and present data from one target cell</Description>
        <Observable>No</Observable>
        <Parameter>
            <Identifier>TargetCell</Identifier>
            <DisplayName>Cell position on the plate</DisplayName>
            <Description>
				Position of the target cell on the plate which the reader will try to find, reach
				and will try to read the cell data
            </Description>
            <DataType>
				<Basic>String</Basic>
            </DataType>
        </Parameter>
		<Response>
            <Identifier>Value</Identifier>
            <DisplayName>Value</DisplayName>
            <Description>Result value of the cell</Description>
            <DataType>
                <Basic>Real</Basic>
            </DataType>
        </Response>
        <StandardExecutionErrors>
            <StandardExecutionErrorIdentifier>CellNotFound</StandardExecutionErrorIdentifier>
            <StandardExecutionErrorIdentifier>ReadInterrupted</StandardExecutionErrorIdentifier>
        </StandardExecutionErrors>
    </Command>
	<Command>
        <Identifier>OpenDoor</Identifier>
        <DisplayName>Open Door</DisplayName>
        <Description>Open the device door</Description>
        <Observable>No</Observable>
        <StandardExecutionErrors>
            <StandardExecutionErrorIdentifier>OpenDoorInterrupted</StandardExecutionErrorIdentifier>
        </StandardExecutionErrors>
    </Command>
	<Command>
        <Identifier>CloseDoor</Identifier>
        <DisplayName>Close Door</DisplayName>
        <Description>Close the device door</Description>
        <Observable>No</Observable>
        <StandardExecutionErrors>
            <StandardExecutionErrorIdentifier>CloseDoorInterrupted</StandardExecutionErrorIdentifier>
        </StandardExecutionErrors>
    </Command>
    <StandardExecutionError>
        <Identifier>CellNotFound</Identifier>
        <DisplayName>Cell Not Found</DisplayName>
        <Description>The destination of the cell not found or cell destination is invalid</Description>
    </StandardExecutionError>
    <StandardExecutionError>
        <Identifier>ReadInterrupted</Identifier>
        <DisplayName>Read Interrupted</DisplayName>
        <Description>Reading the cell was impossible or interrupted</Description>
    </StandardExecutionError>
    <StandardExecutionError>
        <Identifier>OpenDoorInterrupted</Identifier>
        <DisplayName>Open Door Interrupted</DisplayName>
        <Description>Opening the device door was interrupted</Description>
    </StandardExecutionError>
	<StandardExecutionError>
        <Identifier>CloseDoorInterrupted</Identifier>
        <DisplayName>Close Door Interrupted</DisplayName>
        <Description>Closing the device door was interrupted</Description>
    </StandardExecutionError>
</Feature>

=== mcroissant/sila_base/feature_definitions/ch/unitelabs/InitializationController.sila.xml
<?xml version="1.0" encoding="utf-8" ?>
<Feature SiLA2Version="0.2" FeatureVersion="1.0" Originator="ch.unitelabs" Category="instruments"
         xmlns="http://www.sila-standard.org"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.sila-standard.org https://gitlab.com/SiLA2/sila_features/raw/master/schema/FeatureDefinition.xsd">
    <Identifier>InitializationController</Identifier>
    <DisplayName>Initialization Controller</DisplayName>
    <Description>
        Exposes the ability to Initialize an instrument or driver.
    </Description>
    <!-- Commands -->
    <Command>
        <Identifier>Initialize</Identifier>
        <DisplayName>Initialize</DisplayName>
        <Description>Initialize</Description>
        <Observable>No</Observable>
    </Command>
</Feature>

=== mcroissant/sila_base/feature_definitions/com/madisoft/ReaderService.sila.xml
<?xml version="1.0" encoding="utf-8" ?>
<Feature SiLA2Version="0.1" FeatureVersion="1.0" Originator="com.madisoft"
         xmlns="http://www.sila-standard.org"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.sila-standard.org https://gitlab.com/SiLA2/sila_features/raw/master/schema/FeatureDefinition.xsd">
    <Identifier>ReaderService</Identifier>
    <DisplayName>Reader Service</DisplayName>
    <Description>
        SiLA 2 Device Reader example - Show basic operations for a device reader like reading from 
		selected well of a plate, reading all wells in a plate and open/close device cover. There are two
		types of plates with 96 and 384 wells.
    </Description>
	<!-- Commands -->
    <Command>
        <Identifier>ReadWell</Identifier>
        <DisplayName>Read Well</DisplayName>
        <Description>Read and present data from one target well</Description>
        <Observable>No</Observable>
        <Parameter>
            <Identifier>TargetWell</Identifier>
            <DisplayName>Well address on the plate</DisplayName>
            <Description>
				Address of the target well on the plate which the reader will try to find, reach
				and will try to read the well data.
				The plate is ordered list of wells and this addess is the corresponding index of this list
            </Description>
            <DataType>
				<Basic>Integer</Basic>
            </DataType>
        </Parameter>
		<Response>
            <Identifier>Value</Identifier>
            <DisplayName>Value</DisplayName>
            <Description>Result value of the well</Description>
            <DataType>
                <Basic>Real</Basic>
            </DataType>
        </Response>
        <StandardExecutionErrors>
            <StandardExecutionErrorIdentifier>WellNotFound</StandardExecutionErrorIdentifier>
            <StandardExecutionErrorIdentifier>ReadInterrupted</StandardExecutionErrorIdentifier>
        </StandardExecutionErrors>
    </Command>
	<Command>
        <Identifier>ReadPlate</Identifier>
        <DisplayName>Read Plate</DisplayName>
        <Description>Go through every plate well and read its result</Description>
        <Observable>Yes</Observable>
		<Response>
            <Identifier>ResultList</Identifier>
            <DisplayName>Result List Values</DisplayName>
            <Description>Result list of values of every well</Description>
            <DataType>
				<List>
					<DataType>
						<Basic>Real</Basic>
					</DataType>
				</List>
            </DataType>
        </Response>
        <StandardExecutionErrors>
            <StandardExecutionErrorIdentifier>ReadInterrupted</StandardExecutionErrorIdentifier>
        </StandardExecutionErrors>
    </Command>
	<Command>
        <Identifier>OpenCover</Identifier>
        <DisplayName>Open Cover</DisplayName>
        <Description>Open the device cover</Description>
        <Observable>No</Observable>
        <StandardExecutionErrors>
            <StandardExecutionErrorIdentifier>OpenCoverInterrupted</StandardExecutionErrorIdentifier>
        </StandardExecutionErrors>
    </Command>
	<Command>
        <Identifier>CloseCover</Identifier>
        <DisplayName>Close Cover</DisplayName>
        <Description>Close the device cover</Description>
        <Observable>No</Observable>
        <StandardExecutionErrors>
            <StandardExecutionErrorIdentifier>CloseCoverInterrupted</StandardExecutionErrorIdentifier>
        </StandardExecutionErrors>
    </Command>
	<!-- Properties -->
	<Property>
		<Identifier>PlateType</Identifier>
        <DisplayName>Plate Type</DisplayName>
        <Description>
			The plate type for the device reader. Defines plate dimension. Number of wells in the plate.
            Support two types of plates: 96 and 384 wells
        </Description>
        <DataType>
			<Constrained>
                <DataType>
                    <Basic>Integer</Basic>
                </DataType>
                <Constraints>
                    <Enumeration>
                        <Value>96</Value>
                        <Value>384</Value>
                    </Enumeration>
                </Constraints>
            </Constrained>
		</DataType>
		<Observable>No</Observable>
	</Property>
	<Property>
		<Identifier>Status</Identifier>
        <DisplayName>Reader Status</DisplayName>
        <Description>
            Current status of the Reader device
			
			Possible values are:
			- Idle: Reader is online and ready for command execution
			- Busy: Reader is executing a command and because of that is busy and cannot execute other command
			- Unavailable: This combines Offline and Disconnected statuses which means that Reader cannot execute any command or get a property
        </Description>
        <DataType>
			<Constrained>
                <DataType>
                    <Basic>String</Basic>
                </DataType>
                <Constraints>
                    <Enumeration>
                        <Value>Idle</Value>
                        <Value>Busy</Value>
                        <Value>Unavailable</Value>
                    </Enumeration>
                </Constraints>
            </Constrained>
		</DataType>
		<Observable>Yes</Observable>
	</Property>
	<!-- Command Execution Errors -->
    <StandardExecutionError>
        <Identifier>WellNotFound</Identifier>
        <DisplayName>Well Not Found</DisplayName>
        <Description>The destination of the well not found or well destination is invalid</Description>
    </StandardExecutionError>
    <StandardExecutionError>
        <Identifier>ReadInterrupted</Identifier>
        <DisplayName>Read Interrupted</DisplayName>
        <Description>Reading the well was impossible or interrupted</Description>
    </StandardExecutionError>
    <StandardExecutionError>
        <Identifier>OpenCoverInterrupted</Identifier>
        <DisplayName>Open Cover Interrupted</DisplayName>
        <Description>Opening the device cover was interrupted</Description>
    </StandardExecutionError>
	<StandardExecutionError>
        <Identifier>CloseCoverInterrupted</Identifier>
        <DisplayName>Close Cover Interrupted</DisplayName>
        <Description>Closing the device cover was interrupted</Description>
    </StandardExecutionError>
</Feature>

=== mcroissant/sila_base/feature_definitions/org/silastandard/test/ComplexDataTypes2Test.sila.xml
<?xml version="1.0" encoding="utf-8" ?>
<Feature SiLA2Version="1.0" FeatureVersion="1.0" Originator="org.silastandard" Category="test"
         xmlns="http://www.sila-standard.org"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.sila-standard.org https://gitlab.com/SiLA2/sila_base/raw/master/schema/FeatureDefinition.xsd">
    <Identifier>UnobservablePropertyTest</Identifier>
    <DisplayName>Unobservable Property Test</DisplayName>
    <Description>
        Exposes various unobservable properties for test purposes.
    </Description>

    <!-- Data Types -->
    <DataTypeDefinition>
        <Identifier>DataTypeString</Identifier>
        <DisplayName>Data type representing a string</DisplayName>
        <Description></Description>
        <DataType>
            <Basic>String</Basic>
        </DataType>
    </DataTypeDefinition>

    <!-- unobservable Properties -->
    <Property>
        <Identifier>HugeList</Identifier>
        <DisplayName>A Huge List</DisplayName>
        <Description>A list containing a lot of elements</Description>
        <Observable>No</Observable>
        <DataType>
            <List>
                <DataType>
                    <Basic>String</Basic>
                </DataType>
            </List>
        </DataType>
    </Property>

    <Property>
        <Identifier>Boolean</Identifier>
        <DisplayName>Boolean property</DisplayName>
        <Description>Displays a random boolean property</Description>
        <Observable>No</Observable>
        <DataType>
            <Basic>Boolean</Basic>
        </DataType>
    </Property>

    <Property>
        <Identifier>ListString</Identifier>
        <DisplayName>A list of string</DisplayName>
        <Description></Description>
        <Observable>No</Observable>
        <DataType>
            <List>
                <DataType>
                    <Basic>String</Basic>
                </DataType>
            </List>
        </DataType>
    </Property>
    <Property>
        <Identifier>RandomChangingListString</Identifier>
        <DisplayName>A randomly changing list of strings</DisplayName>
        <Description></Description>
        <Observable>No</Observable>
        <DataType>
            <List>
                <DataType>
                    <Basic>String</Basic>
                </DataType>
            </List>
        </DataType>
    </Property>

    <Property>
        <Identifier>ListStructPairString</Identifier>
        <DisplayName>A list of structure with a pair of string</DisplayName>
        <Description></Description>
        <Observable>No</Observable>
        <DataType>
            <List>
                <DataType>
                    <Structure>
                        <Element>
                            <Identifier>Key</Identifier>
                            <DisplayName>Key</DisplayName>
                            <Description>The key</Description>
                            <DataType>
                                <Basic>String</Basic>
                            </DataType>
                        </Element>
                        <Element>
                            <Identifier>Value</Identifier>
                            <DisplayName>Value</DisplayName>
                            <Description>The value</Description>
                            <DataType>
                                <Basic>String</Basic>
                            </DataType>
                        </Element>
                    </Structure>
                </DataType>
            </List>
        </DataType>
    </Property>

    <Property>
        <Identifier>StructPairString</Identifier>
        <DisplayName>A structure with a pair of string</DisplayName>
        <Description></Description>
        <Observable>No</Observable>
        <DataType>
            <Structure>
                <Element>
                    <Identifier>PairString</Identifier>
                    <DisplayName>Pair String</DisplayName>
                    <Description>Pair of String</Description>
                    <DataType>
                        <Structure>
                            <Element>
                                <Identifier>Key</Identifier>
                                <DisplayName>Key</DisplayName>
                                <Description>The key</Description>
                                <DataType>
                                    <Basic>String</Basic>
                                </DataType>
                            </Element>
                            <Element>
                                <Identifier>Value</Identifier>
                                <DisplayName>Value</DisplayName>
                                <Description>The value</Description>
                                <DataType>
                                    <Basic>String</Basic>
                                </DataType>
                            </Element>
                        </Structure>
                    </DataType>
                </Element>
            </Structure>
        </DataType>
    </Property>

    <Property>
        <Identifier>DataType</Identifier>
        <DisplayName>A Datatype</DisplayName>
        <Description></Description>
        <Observable>No</Observable>
        <DataType>
            <DataTypeIdentifier>DataTypeString</DataTypeIdentifier>
        </DataType>
    </Property>

    <Property>
        <Identifier>ThrowException</Identifier>
        <DisplayName>Throw a test exception</DisplayName>
        <Description></Description>
        <Observable>No</Observable>
        <DataType>
            <Basic>String</Basic>
        </DataType>
    </Property>

    <!-- Execution Errors -->
    <DefinedExecutionError>
        <Identifier>TestException</Identifier>
        <DisplayName>Test Exception</DisplayName>
        <Description>
            You just encountered a test exception !
        </Description>
    </DefinedExecutionError>
</Feature>

=== mcroissant/sila_base/feature_definitions/org/silastandard/core/AuthorizationService.xml
<?xml version="1.0" encoding="utf-8" ?>
<Feature SiLAVersion="2" MajorVersion="1" MinorVersion="0" MaturityLevel="Draft" Originator="org.silastandard" Category="core"
         xmlns="http://www.sila-standard.org"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.sila-standard.org https://gitlab.com/SiLA2/sila_base/raw/master/schema/FeatureDefinition.xsd">
    <Identifier>AuthorizationService</Identifier>
    <DisplayName>Authorization Service</DisplayName>
    <Description>This Feature provides access control for the implementing server.
        Therefore it specifies the SiLA Client Meta Data for the access token, that has been provided by the AuthenticationService.
        In order to use the servers functionlity, that access token has to be sent with every call to server.</Description>
    <StandardExecutionError>
        <Identifier>InvalidAccessToken</Identifier>
        <DisplayName>Invalid Access Token</DisplayName>
        <Description>The sent access token is not valid (lifetime might have exceeded)</Description>
    </StandardExecutionError>
    <StandardExecutionError>
        <Identifier>NotAuthorized</Identifier>
        <DisplayName>Not Authorized</DisplayName>
        <Description>The sent access token does not authorize to access the required SiLA Server functionality</Description>
    </StandardExecutionError>
    <Metadata>
        <Identifier>AccessToken</Identifier>
        <DisplayName>AccessToken</DisplayName>
        <Description>Token to be sent with every call in order to get access to the SiLA Server functionality</Description>
        <DataType>
            <Basic>String</Basic>
        </DataType>
        <SendWith>All</SendWith>
    </Metadata>
</Feature>
