=== mcroissant/sila_base/schema/FeatureDefinition.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" 
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:tns="http://www.sila-standard.org"
    xmlns:dta="http://www.sila-standard.org/Data"
    targetNamespace="http://www.sila-standard.org">
  <xs:import namespace="http://www.sila-standard.org/Data" schemaLocation="DataTypeType.xsd"/>
  <xs:element name="Feature">
    <xs:complexType>
      <!-- Feature Content -->
      <xs:sequence>
        <xs:element type="tns:IdentifierType" name="Identifier" />
        <xs:element type="tns:DisplayNameType" name="DisplayName" />
        <xs:element type="xs:string" name="Description" />
        <!-- @Note: xs:all can not be used here, as it doesn't allow unbounded occurences -->
        <xs:choice maxOccurs="unbounded">
          <xs:element name="Command" maxOccurs="unbounded" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element type="tns:IdentifierType" name="Identifier" />
                <xs:element type="tns:DisplayNameType" name="DisplayName" />
                <xs:element type="xs:string" name="Description" />
                <xs:element name="Observable">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:enumeration value="Yes" />
                      <xs:enumeration value="No" />
                    </xs:restriction>
                  </xs:simpleType>
                </xs:element>
                <xs:element type="tns:SiLAElement" name="Parameter" maxOccurs="unbounded" minOccurs="0" />
                <xs:element type="tns:SiLAElement" name="Response" maxOccurs="unbounded" minOccurs="0" />
                <xs:element type="tns:SiLAElement" name="IntermediateResponse" maxOccurs="unbounded" minOccurs="0" />
                <xs:element name="StandardExecutionErrors" maxOccurs="1" minOccurs="0">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element type="tns:IdentifierType" name="StandardExecutionErrorIdentifier" maxOccurs="unbounded" minOccurs="1" />
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="StandardExecutionError" maxOccurs="unbounded" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element type="tns:IdentifierType" name="Identifier" />
                <xs:element type="tns:DisplayNameType" name="DisplayName" />
                <xs:element type="xs:string" name="Description" />
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="Property" maxOccurs="unbounded" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element type="tns:IdentifierType" name="Identifier" />
                <xs:element type="tns:DisplayNameType" name="DisplayName" />
                <xs:element type="xs:string" name="Description" />
                <xs:element type="dta:DataTypeType" name="DataType" />
                <xs:element name="Observable">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:enumeration value="Yes" />
                      <xs:enumeration value="No" />
                    </xs:restriction>
                  </xs:simpleType>
                </xs:element>
                <xs:element name="StandardReadErrors" maxOccurs="1" minOccurs="0">
                  <xs:complexType>
                    <xs:sequence>
                      <xs:element type="tns:IdentifierType" name="StandardReadErrorIdentifier" maxOccurs="unbounded" minOccurs="1" />
                    </xs:sequence>
                  </xs:complexType>
                </xs:element>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element name="StandardReadError" maxOccurs="unbounded" minOccurs="0">
            <xs:complexType>
              <xs:sequence>
                <xs:element type="tns:IdentifierType" name="Identifier" />
                <xs:element type="tns:DisplayNameType" name="DisplayName" />
                <xs:element type="xs:string" name="Description" />
              </xs:sequence>
            </xs:complexType>
          </xs:element>
          <xs:element type="tns:SiLAElement" name="DataTypeDefinition" maxOccurs="unbounded" minOccurs="0" />
        </xs:choice>
      </xs:sequence>

      <!-- Attributes -->
      <xs:attribute type="xs:string" name="Locale" use="optional" default="en-us" />
      <xs:attribute name="SiLA2Version" use="required">
        <xs:simpleType>
          <xs:restriction base ="xs:string">
            <xs:pattern value="\d+\.\d+" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="FeatureVersion" use="required">
        <xs:simpleType>
          <xs:restriction base ="xs:string">
            <xs:pattern value="\d+\.\d+" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="MaturityLevel" use="optional" default="Draft">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="Draft" />
            <xs:enumeration value="Verified" />
            <xs:enumeration value="Normative" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="Originator" use="required">
        <xs:simpleType>
          <xs:restriction base ="xs:string">
            <xs:pattern value="[a-z][a-z\.]*" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="Category" use="optional">
        <xs:simpleType>
          <xs:restriction base ="xs:string">
            <xs:pattern value="[a-z][a-z\.]*" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <!-- XSD Internal Types -->
  <xs:simpleType name="IdentifierType">
    <xs:restriction base ="xs:string">
      <xs:pattern value="[A-Z][a-zA-Z0-9]*" />
      <xs:maxLength value="255" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="DisplayNameType">
    <xs:restriction base ="xs:string">
      <xs:maxLength value="255" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="SiLAElement">
    <xs:sequence>
      <xs:element type="tns:IdentifierType" name="Identifier" />
      <xs:element type="tns:DisplayNameType" name="DisplayName" />
      <xs:element type="xs:string" name="Description" />
      <xs:element type="dta:DataTypeType" name="DataType" />
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="BasicType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="String"/>
      <xs:enumeration value="Integer"/>
      <xs:enumeration value="Real"/>
      <xs:enumeration value="Boolean"/>
      <xs:enumeration value="SmallBinary"/>
      <xs:enumeration value="Date"/>
      <xs:enumeration value="Time"/>
      <xs:enumeration value="Timestamp"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="ListType">
    <xs:sequence>
      <xs:element type="dta:DataTypeType" name="DataType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="StructureType">
    <xs:sequence>
      <xs:element type="tns:SiLAElement" name = "Element" maxOccurs="unbounded" minOccurs="1" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== mcroissant/sila_base/feature_definitions/org/silastandard/examples/MonitoringService.sila.xml
<?xml version="1.0" encoding="utf-8" ?>
<Feature SiLA2Version="0.1" FeatureVersion="1.0" MaturityLevel="Draft" Originator="org.silastandard" Category="examples"
        xmlns="http://www.sila-standard.org"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.sila-standard.org https://gitlab.com/SiLA2/sila_base/raw/master/schema/FeatureDefinition.xsd">
    <Identifier>MonitoringService</Identifier>
    <DisplayName>Monitoring Service</DisplayName>
    <Description>
        Provides the monitoring of activity around feature executions of SiLA Servers.
    </Description>
    <Property>
        <Identifier>CommandExecution</Identifier>
        <DisplayName>Command Execution</DisplayName>
        <Description>Recent Command Execution triggered and finished on the SiLA Server</Description>
        <DataType>
            <Structure>
                <Element>
                    <Identifier>FeatureIdentifier</Identifier>
                    <DisplayName>Feature Identifier</DisplayName>
                    <Description/>
                    <DataType>
                        <Basic>String</Basic>
                    </DataType>
                </Element>
                <Element>
                    <Identifier>CommandIdentifier</Identifier>
                    <DisplayName>Command Identifier</DisplayName>
                    <Description/>
                    <DataType>
                        <Basic>String</Basic>
                    </DataType>
                </Element>
                <Element>
                    <Identifier>Parameters</Identifier>
                    <DisplayName>Parameters</DisplayName>
                    <Description/>
                    <DataType>
                        <Basic>Any</Basic>
                    </DataType>
                </Element>
                <Element>
                    <Identifier>Results</Identifier>
                    <DisplayName>Results</DisplayName>
                    <Description/>
                    <DataType>
                        <Basic>Any</Basic>
                    </DataType>
                </Element>
            </Structure>
        </DataType>
        <Observable>Yes</Observable>
    </Property>
</Feature>

=== mcroissant/sila_base/feature_definitions/org/silastandard/test/ParameterConstraintsProviderTest.sila.xml
<?xml version="1.0" encoding="utf-8" ?>
<Feature SiLA2Version="1.0" FeatureVersion="1.0" Originator="org.silastandard" Category="test"
         xmlns="http://www.sila-standard.org"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.sila-standard.org https://gitlab.com/SiLA2/sila_base/raw/master/schema/FeatureDefinition.xsd">
    <Identifier>ParameterConstraintsProviderTest</Identifier>
    <DisplayName>Parameter Constraints Provider Test</DisplayName>
    <Description>
        Simple feature on which implementation of the parameter constraint provider is shown.
    </Description>

    <DataTypeDefinition>
        <Identifier>Position</Identifier>
        <DisplayName>Position</DisplayName>
        <Description>Position</Description>
        <DataType>
            <Structure>
                <Element>
                    <Identifier>Identifier</Identifier>
                    <DisplayName>Identifier</DisplayName>
                    <Description>Identifier</Description>
                    <DataType>
                        <Basic>String</Basic>
                    </DataType>
                </Element>
                <Element>
                    <Identifier>X</Identifier>
                    <DisplayName>X</DisplayName>
                    <Description>X</Description>
                    <DataType>
                        <Basic>Integer</Basic>
                    </DataType>
                </Element>
                <Element>
                    <Identifier>Y</Identifier>
                    <DisplayName>Y</DisplayName>
                    <Description>Y</Description>
                    <DataType>
                        <Basic>Integer</Basic>
                    </DataType>
                </Element>
            </Structure>
        </DataType>
    </DataTypeDefinition>

    <Command>
        <Identifier>GoToPos</Identifier>
        <DisplayName>Go to position</DisplayName>
        <Description>Ask the robot to go to the specified position</Description>
        <Observable>No</Observable>
        <Parameter>
            <Identifier>PositionIdentifier</Identifier>
            <DisplayName>PositionIdentifier</DisplayName>
            <Description>The position identifier</Description>
            <DataType>
                <Basic>String</Basic>
            </DataType>
        </Parameter>
    </Command>

    <Command>
        <Identifier>AddPosition</Identifier>
        <DisplayName>Add position</DisplayName>
        <Description>Add a position</Description>
        <Observable>No</Observable>
        <Parameter>
            <Identifier>Position</Identifier>
            <DisplayName>The position</DisplayName>
            <Description>The position to add</Description>
            <DataType>
                <DataTypeIdentifier>Position</DataTypeIdentifier>
            </DataType>
        </Parameter>
    </Command>

    <Command>
        <Identifier>RemovePosition</Identifier>
        <DisplayName>Remove position</DisplayName>
        <Description>Remove a position</Description>
        <Observable>No</Observable>
        <Parameter>
            <Identifier>Identifier</Identifier>
            <DisplayName>The position identifier</DisplayName>
            <Description>The position identifier to remove</Description>
            <DataType>
                <Basic>String</Basic>
            </DataType>
        </Parameter>
    </Command>

    <Property>
        <Identifier>Positions</Identifier>
        <DisplayName>Positions</DisplayName>
        <Description>Positions</Description>
        <Observable>No</Observable>
        <DataType>
            <List>
                <DataType>
                    <DataTypeIdentifier>Position</DataTypeIdentifier>
                </DataType>
            </List>
        </DataType>
    </Property>
</Feature>

=== mcroissant/sila_base/FeatureDefinitionViewer/bin/Debug/AppX/src/feature/StorageControler.xml
<?xml version='1.0' encoding='utf-8' ?>
<Feature SiLAVersion='2' MajorVersion='1' MinorVersion='0' MaturityLevel='Draft' Originator='de.tuberlin.bioprocess' UseCase='storing'
        xmlns='http://www.sila-standard.org'
        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xsi:schemaLocation='http://www.sila-standard.org https://gitlab.com/SiLA2/sila_features/raw/master/schema/FeatureDefinition.xsd'>
  <Identifier>StorageControler</Identifier>
  <DisplayName>Storage Controler</DisplayName>
  <Description>Controles a storage device</Description>
  <Command>
    <!--GetFromPosition-->
    <Identifier>GetFromPosition</Identifier>
    <DisplayName>Get From Position</DisplayName>
    <Description>Get a Labware from the specified position and presents it to the addressed handover position</Description>
    <Observable>No</Observable>
    <Parameter>
      <Identifier>AttainablePosition</Identifier>
      <DisplayName>Attainable Position</DisplayName>
      <Description>Postion of the labware in the storage device</Description>
      <DataType>
        <Basic>Integer</Basic>
      </DataType>
    </Parameter>
    <Response>
      <Identifier>HandoverPosition</Identifier>
      <DisplayName>Handover Postion</DisplayName>
      <Description>Postion of the labware handover</Description>
      <DataType>
        <Basic>Integer</Basic>
      </DataType>
    </Response>
    <StandardExecutionErrors>
      <StandardExecutionErrorIdentifier>ExcituctionError</StandardExecutionErrorIdentifier>
      <StandardExecutionErrorIdentifier>InvaldPosition</StandardExecutionErrorIdentifier>
    </StandardExecutionErrors>
  </Command>
  <Command>
    <!--PutFromPosition-->
    <Identifier>PutToPosition</Identifier>
    <DisplayName>Put To Position</DisplayName>
    <Description>Take a labware from the addressed handover position an stores it at the specified position</Description>
    <Observable>No</Observable>
    <Parameter>
      <Identifier>AttainablePosition</Identifier>
      <DisplayName>Attainable Position</DisplayName>
      <Description>Postion in the storage device where the labware will be stored</Description>
      <DataType>
        <Basic>Integer</Basic>
      </DataType>
    </Parameter>
    <Response>
      <Identifier>HandoverPosition</Identifier>
      <DisplayName>Handover Postion</DisplayName>
      <Description>Postion of the labware handover</Description>
      <DataType>
        <Basic>Integer</Basic>
      </DataType>
    </Response>
    <StandardExecutionErrors>
      <StandardExecutionErrorIdentifier>InvaldPosition</StandardExecutionErrorIdentifier>
      <StandardExecutionErrorIdentifier>ExcituctionError</StandardExecutionErrorIdentifier>
    </StandardExecutionErrors>
  </Command>
</Feature>

=== mcroissant/sila_base/feature_definitions/org/silastandard/core/AuthorizationService.sila.xml
<?xml version="1.0" encoding="utf-8" ?>
<Feature SiLA2Version="0.1" FeatureVersion="1.0" MaturityLevel="Draft" Originator="org.silastandard" Category="core"
         xmlns="http://www.sila-standard.org"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.sila-standard.org https://gitlab.com/SiLA2/sila_base/blob/meta_data/schema/FeatureDefinition.xsd">
    <Identifier>AuthorizationService</Identifier>
    <DisplayName>Authorization Service</DisplayName>
    <Description>
        This Feature provides access control for the implementing server.

        Therefore it specifies the SiLA Client Meta Data for the access token, that has been provided by the
        AuthenticationService core Feature.
    </Description>
    <Metadata>
        <Identifier>AccessToken</Identifier>
        <DisplayName>AccessToken</DisplayName>
        <Description>Token to be sent with every call in order to get access to the SiLA Server functionality.</Description>
        <DataType>
            <Basic>String</Basic>
        </DataType>
    </Metadata>
</Feature>

=== mcroissant/sila_base/feature_definitions/de/tuberlin/bioprocess/ServerInfomationProvider.sila.xml
<?xml version="1.0" encoding="utf-8" ?>
<Feature SiLAVersion="2" MajorVersion="1" MinorVersion="0" MaturityLevel="Draft" Originator="de.tuberlin.bioprocess" Category="briefing"
        xmlns="http://www.sila-standard.org" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.sila-standard.org https://gitlab.com/SiLA2/sila_features/raw/master/schema/FeatureDefinition.xsd">
    <Identifier>DeviceInformationProvider</Identifier>
    <DisplayName>Device Information Provider</DisplayName>
    <Description>Provides meta data about the hardware device of the used SiLA Server</Description>
    <Property>
        <Identifier>DeviceSuperior</Identifier>
        <DisplayName>Device Superior</DisplayName>
        <Description>Contact of the person how take care for the device</Description>
        <DataType>
          <Basic>String</Basic>
        </DataType>
        <Observable>No</Observable>
    </Property>
    <Property>
        <Identifier>RoomNumber</Identifier>
        <DisplayName>Room Number</DisplayName>
        <Description>Room Number where the device is located</Description>
        <DataType>
            <Basic>String</Basic>
        </DataType>
        <Observable>No</Observable>
    </Property>
    <Property>
      <Identifier>EmergencyContact</Identifier>
      <DisplayName>Emergency Contact</DisplayName>
      <Description>A contact number or email address of a person to call in case of an accident of the device (not of a person)</Description>
      <DataType>
        <Basic>String</Basic>
      </DataType>
      <Observable>No</Observable>
    </Property>
    <Property>
        <Identifier>FirmwareVersion</Identifier>
        <DisplayName>Firmware Version</DisplayName>
        <Description>Firmware Version of the Device</Description>
        <DataType>
            <Basic>String</Basic>
        </DataType>
        <Observable>No</Observable>
    </Property>
    </Feature>

=== mcroissant/sila_base/feature_definitions/org/silastandard/examples/MonitoringService.xml
<?xml version="1.0" encoding="utf-8" ?>
<Feature SiLAVersion="2" MajorVersion="1" MinorVersion="0" MaturityLevel="Draft" Originator="org.silastandard" UseCase="examples"
        xmlns="http://www.sila-standard.org"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.sila-standard.org https://gitlab.com/SiLA2/sila_base/raw/master/schema/FeatureDefinition.xsd">
    <Identifier>MonitoringService</Identifier>
    <DisplayName>Monitoring Service</DisplayName>
    <Description>
        Provides the monitoring of activity around feature executions of SiLA Servers.
    </Description>
    <Property>
        <Identifier>CommandExecution</Identifier>
        <DisplayName>Command Execution</DisplayName>
        <Description>Recent Command Execution triggered and finished on the SiLA Server</Description>
        <DataType>
            <Structure>
                <Element>
                    <Identifier>FeatureIdentifier</Identifier>
                    <DataType>
                        <Basic>String</Basic>
                    </DataType>
                </Element>
                <Element>
                    <Identifier>CommandIdentifier</Identifier>
                    <DataType>
                        <Basic>String</Basic>
                    </DataType>
                </Element>
                <Element>
                    <Identifier>Parameters</Identifier>
                    <DataType>
                        <Basic>Any</Basic>
                    </DataType>
                </Element>
                <Element>
                    <Identifier>Results</Identifier>
                    <DataType>
                        <Basic>Any</Basic>
                    </DataType>
                </Element>
            </Structure>
        </DataType>
        <Observable>Yes</Observable>
    </Property>
</Feature>

=== mcroissant/sila_base/feature_definitions/org/silastandard/test/UnobservablePropertyTest.sila.xml
<?xml version="1.0" encoding="utf-8" ?>
<Feature SiLA2Version="1.0" FeatureVersion="1.0" Originator="org.silastandard" Category="test"
         xmlns="http://www.sila-standard.org"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://www.sila-standard.org https://gitlab.com/SiLA2/sila_base/raw/master/schema/FeatureDefinition.xsd">
    <Identifier>UnobservablePropertyTest</Identifier>
    <DisplayName>Unobservable Property Test</DisplayName>
     <Description>
        This is a test feature to generically test Unobservable properties.
        It specifies various unobservable properties and returns defined answers to validate against.
        We provide three different properties for testing concurrent situations.
        The Server should iterate 1000 times (to produce some load) and return the final count as Integer.
        By that we produce an predictable output/return which could be easily tested.
    </Description>

    <!-- Unobservable Properties -->
    <Property>
        <Identifier>UnobservablePropertyIteration1</Identifier>
        <DisplayName>Unobservable Property iteration no. 1</DisplayName>
        <Description>Unobservable Property iteration no. 1, running 1000 times and returning the current final result.</Description>
        <Observable>No</Observable>
        <DataType>
            <Basic>Integer</Basic>
        </DataType>
    </Property>
    <Property>
        <Identifier>UnobservablePropertyIteration2</Identifier>
        <DisplayName>Unobservable Property iteration no. 2</DisplayName>
        <Description>Unobservable Property iteration no. 2, running 1000 times and returning the final result.</Description>
        <Observable>No</Observable>
        <DataType>
            <Basic>Integer</Basic>
        </DataType>
    </Property>
        <Property>
        <Identifier>UnobservablePropertyIteration3</Identifier>
        <DisplayName>Unobservable Property iteration no. 3</DisplayName>
        <Description>Unobservable Property iteration no. 3, running 1000 times and returning the final result.</Description>
        <Observable>No</Observable>
        <DataType>
            <Basic>Integer</Basic>
        </DataType>
    </Property>

</Feature>
