=== mcroissant/sila_base/schema/current/sila-feature.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.sila-standard.org"
        targetNamespace="http://www.sila-standard.org" elementFormDefault="qualified">
    <element name="SiLA">
        <complexType>
            <sequence>
                <element name="Feature" type="tns:Feature" minOccurs="1" maxOccurs="1"/>
            </sequence>
            <attribute name="version">
                <simpleType>
                    <restriction base="string">
                        <enumeration value="2.0"/>
                    </restriction>
                </simpleType>
            </attribute>
        </complexType>
    </element>

    <simpleType name="identifier">
        <restriction base="string">
            <pattern value="[A-Z][a-zA-Z0-9]*"/>
        </restriction>
    </simpleType>

    <complexType name="Base">
        <sequence >
            <element type="tns:identifier" name="Identifier" minOccurs="1" maxOccurs="1"/>
            <element type="string" name="DisplayName" minOccurs="1" maxOccurs="1"/>
            <element type="string" name="Description" minOccurs="1" maxOccurs="1"/>
        </sequence>
    </complexType>

    <complexType name="DataObject">
        <complexContent>
            <extension base="tns:Base">
                <sequence>
                    <element name="DataType">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="String"/>
                                <enumeration value="Integer"/>
                                <enumeration value="Real"/>
                                <enumeration value="Binary"/>
                                <enumeration value="Boolean"/>
                                <enumeration value="Date"/>
                                <enumeration value="Time"/>
                                <enumeration value="Timestamp"/>
                                <enumeration value="String[]"/>
                                <enumeration value="Integer[]"/>
                                <enumeration value="Real[]"/>
                                <enumeration value="Boolean[]"/>
                                <enumeration value="Date[]"/>
                                <enumeration value="Time[]"/>
                                <enumeration value="Timestamp[]"/>
                            </restriction>
                        </simpleType>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Feature">
        <complexContent>
            <extension base="tns:Base">
                <sequence>
                    <element name="Command" maxOccurs="unbounded" minOccurs="0"
                             type="tns:Command"/>
                    <element name="Property" maxOccurs="unbounded" minOccurs="0"
                             type="tns:Property"/>
                    <element name="StandardError" maxOccurs="unbounded" minOccurs="0"
                             type="tns:StandardError"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Command">
        <complexContent>
            <extension base="tns:Base">
                <sequence>
                    <element name="Observable">
                        <simpleType>
                            <restriction base="string">
                                <!-- <enumeration value="Yes"/> -->
                                <enumeration value="No"/>
                            </restriction>
                        </simpleType>
                    </element>
                    <element name="Parameter" maxOccurs="unbounded" minOccurs="0"
                             type="tns:DataObject"/>
                    <element name="Response" maxOccurs="1" minOccurs="0"
                             type="tns:DataObject"/>
                    <element name="StandardErrors" maxOccurs="1" minOccurs="0">
                        <complexType>
                            <sequence>
                                <element name="Identifier" type="tns:identifier" maxOccurs="unbounded" minOccurs="0"/>
                            </sequence>
                        </complexType>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Property">
        <complexContent>
            <extension base="tns:DataObject">
                <sequence>
                    <element name="PropertyType">
                        <simpleType>
                            <restriction base="string">
                                <enumeration value="Static"/>
                                <!-- <enumeration value="Dynamic"/> -->
                            </restriction>
                        </simpleType>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="StandardError">
        <complexContent>
            <extension base="tns:Base">
            </extension>
        </complexContent>
    </complexType>

    <complexType name="DataType">
        <sequence>
            <element type="tns:identifier" name="Identifier"/>
            <element type="string" name="Definition"/>
        </sequence>
    </complexType>
</schema>

=== mcroissant/sila_base/definitions/SiLAService.xml
<?xml version="1.0"?>

<SiLA version="2.0"
      xmlns="http://www.sila-standard.org"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.sila-standard.org ../schema/current/sila-feature.xsd">

    <Feature>
        <Identifier>SiLAService</Identifier>
        <DisplayName>SiLA Service</DisplayName>
        <Description>The Feature each SiLA Device MUST implement. It is the entry point to a SiLA Device and
            helps to discover the Features it implements.</Description>
        <Command>
            <Identifier>GetFeatureDefinition</Identifier>
            <DisplayName>Get Feature Definition</DisplayName>
            <Description>Get all details on one Feature through the Feature id.</Description>
            <ExecutionBehaviour>Immediate</ExecutionBehaviour>
            <Parameter>
                <Identifier>FeatureIdentifier</Identifier>
                <DisplayName>Feature Identifier</DisplayName>
                <Description>The Feature identifier for which the Feature description should be retrieved.
                    </Description>
                <DataType>String</DataType>
            </Parameter>
            <Response>
                <Identifier>FeatureDefinition</Identifier>
                <DisplayName>Feature Definition</DisplayName>
                <Description>The Feature Definition as XML File. (temporary)</Description>
                <DataType>Binary</DataType>
            </Response>
        </Command>
        <Property>
            <Identifier>DeviceDisplayName</Identifier>
            <DisplayName>Device Display Name</DisplayName>
            <Description>Human readable name of the SiLA Device.</Description>
            <DataType>String</DataType>
            <PropertyType>Static</PropertyType>
        </Property>
        <Property>
            <Identifier>ImplementedFeatures</Identifier>
            <DisplayName>Implemented Features</DisplayName>
            <Description>Returns a list of qualified Feature identifiers of all implemented Features of
                this SiLA Device.</Description>
            <DataType>String[]</DataType>
            <PropertyType>Static</PropertyType>
        </Property>
        <Property>
            <Identifier>DeviceVendorURI</Identifier>
            <DisplayName>URI of Device Vendor</DisplayName>
            <Description>Returns the URI to the website of the vendor or the
                website of the product of this SiLA Device.</Description>
            <DataType>String</DataType>
            <PropertyType>Static</PropertyType>
        </Property>
    </Feature>

</SiLA>

=== mcroissant/sila_base/schema/examples/sila-feature-example01.xml
<?xml version="1.0" ?>
<SiLA version="2.0"
      xmlns="http://www.sila-standard.org"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.sila-standard.org ../current/sila-feature.xsd">
    <Feature>
        <Identifier>Feature1</Identifier>
        <DisplayName>string</DisplayName>
        <Description>string</Description>
        <Command>
            <Identifier>Command1</Identifier>
            <DisplayName>Command No 1</DisplayName>
            <Description>Some Command Description</Description>
            <ExecutionBehaviour>Immediate</ExecutionBehaviour>
            <Parameter>
                <Identifier>P1</Identifier>
                <DisplayName>Parameter 1</DisplayName>
                <Description>Some String Array</Description>
                <DataType>String[]</DataType>
            </Parameter>
            <Parameter>
                <Identifier>P2</Identifier>
                <DisplayName>Boolean</DisplayName>
                <Description>Boolean</Description>
                <DataType>Boolean</DataType>
            </Parameter>
            <Response>
                <Identifier>R1</Identifier>
                <DisplayName>Integer</DisplayName>
                <Description>Integer</Description>
                <DataType>Integer</DataType>
            </Response>
            <StandardErrors>
                <Identifier>SomeError</Identifier>
                <Identifier>SomeErro2</Identifier>
            </StandardErrors>
        </Command>
        <!--Zero or more repetitions:-->
        <Property>
            <Identifier>MyProperty</Identifier>
            <DisplayName>string</DisplayName>
            <Description>string</Description>
            <DataType>string</DataType>
            <PropertyType>Static</PropertyType>
        </Property>
        <StandardError>
            <Identifier>SomeError</Identifier>
            <DisplayName>Some Error</DisplayName>
            <Description>It is an Error</Description>
        </StandardError>
        <StandardError>
            <Identifier>SomeError2</Identifier>
            <DisplayName>Some Error2</DisplayName>
            <Description>It is an Error2</Description>
        </StandardError>
    </Feature>
</SiLA>

=== mcroissant/sila_base/schema/examples/sila-feature-example02.xml
<?xml version="1.0" ?>
<SiLA version="2.0" xmlns="http://www.sila-standard.org"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.sila-standard.org ../current/sila-feature.xsd">
    <Feature>
        <Identifier>MyOtherFeature</Identifier>
        <DisplayName>My Other Feature</DisplayName>
        <Description>Some Description</Description>
        <Command>
            <Identifier>CommandNoResponse</Identifier>
            <DisplayName>Command No Response</DisplayName>
            <Description>Command without a response or parameters</Description>
            <ExecutionBehaviour>Immediate</ExecutionBehaviour>
        </Command>
    </Feature>
</SiLA>
